In [13]:
#Import dependencies
import pandas as pd
import numpy as np
import os

In [14]:
base_path= 'Output/'
denue_df = pd.read_csv(f'{base_path}denue_total.csv')
pib_df = pd.read_csv(f'{base_path}pib.csv')

In [15]:
denue_df.head()

,Unnamed: 0,CVE_ENT,CODIGO,ID_ESTRATO,Unidades 2019,Unidades 2020,DELTA UNIDADES_ECONOMICAS
0,0,1,21,0 a 5 personas,3,4,1
1,1,1,21,6 a 10 personas,3,3,0
2,2,1,22,0 a 5 personas,22,42,20
3,3,1,22,6 a 10 personas,9,8,-1
4,4,1,23,0 a 5 personas,161,245,84

In [16]:
pib_df.head()

,Concepto,CODIGO,2019 - 9 Meses,2020 - 9 Meses,DELTA PIB
0,"11 - Agricultura, cría y explotación de animal...",11,560500.805,565151.496,0.829739
1,21 - Minería,21,857631.916,850685.271,-0.809980
2,"22 - Generación, transmisión y distribución de...",22,286079.166,270881.436,-5.312421
3,23 - Construcción,23,1235196.591,993075.226,-19.601849
4,43 - Comercio al por mayor,43,1551317.935,1372900.386,-11.501031

In [17]:
column_names = ["CODIGO", "DELTA PIB","ID_ESTRATO"]
pib2_df = pd.DataFrame(columns =  column_names)

for cod, delta in pib_df[["CODIGO", "DELTA PIB"]].values:
    df2 = pd.DataFrame([[cod, delta, "0 a 5 personas"], [cod, delta, "6 a 10 personas"]], columns = column_names)
    pib2_df = pib2_df.append(df2, ignore_index = True)

pib2_df

    CODIGO  DELTA PIB       ID_ESTRATO
0     11.0   0.829739   0 a 5 personas
1     11.0   0.829739  6 a 10 personas
2     21.0  -0.809980   0 a 5 personas
3     21.0  -0.809980  6 a 10 personas
4     22.0  -5.312421   0 a 5 personas
5     22.0  -5.312421  6 a 10 personas
6     23.0 -19.601849   0 a 5 personas
7     23.0 -19.601849  6 a 10 personas
8     43.0 -11.501031   0 a 5 personas
9     43.0 -11.501031  6 a 10 personas
10    46.0 -12.680626   0 a 5 personas
11    46.0 -12.680626  6 a 10 personas
12    51.0  -1.411350   0 a 5 personas
13    51.0  -1.411350  6 a 10 personas
14    52.0  -2.431133   0 a 5 personas
15    52.0  -2.431133  6 a 10 personas
16    53.0  -0.282731   0 a 5 personas
17    53.0  -0.282731  6 a 10 personas
18    54.0  -6.334032   0 a 5 personas
19    54.0  -6.334032  6 a 10 personas
20    55.0  -9.136960   0 a 5 personas
21    55.0  -9.136960  6 a 10 personas
22    56.0  -0.269750   0 a 5 personas
23    56.0  -0.269750  6 a 10 personas
24    61.0  -3.987116   0 a 5 personas
25    61.0  -3.987116  6 a 10 personas
26    62.0   0.322008   0 a 5 personas
27    62.0   0.322008  6 a 10 personas
28    71.0 -53.929670   0 a 5 personas
29    71.0 -53.929670  6 a 10 personas
30    72.0 -44.530806   0 a 5 personas
31    72.0 -44.530806  6 a 10 personas
32    81.0 -14.735783   0 a 5 personas
33    81.0 -14.735783  6 a 10 personas
34    93.0   3.344679   0 a 5 personas
35    93.0   3.344679  6 a 10 personas

In [19]:
merge_df = pd.merge(denue_df, pib_df, on="CODIGO")
merge_df

,Unnamed: 0,CVE_ENT,CODIGO,ID_ESTRATO,Unidades 2019,Unidades 2020,DELTA UNIDADES_ECONOMICAS,Concepto,2019 - 9 Meses,2020 - 9 Meses,DELTA PIB
0,0,1,21,0 a 5 personas,3,4,1,21 - Minería,857631.916,850685.271,-0.809980
1,1,1,21,6 a 10 personas,3,3,0,21 - Minería,857631.916,850685.271,-0.809980
2,41,2,21,0 a 5 personas,16,19,3,21 - Minería,857631.916,850685.271,-0.809980
3,42,2,21,6 a 10 personas,16,14,-2,21 - Minería,857631.916,850685.271,-0.809980
4,82,3,21,0 a 5 personas,12,17,5,21 - Minería,857631.916,850685.271,-0.809980
...,...,...,...,...,...,...,...,...,...,...,...
992,1234,30,81,6 a 10 personas,2161,2190,29,81 - Otros servicios excepto actividades guber...,366218.067,312252.967,-14.735783
993,1275,31,81,0 a 5 personas,15342,15371,29,81 - Otros servicios excepto actividades guber...,366218.067,312252.967,-14.735783
994,1276,31,81,6 a 10 personas,1026,1045,19,81 - Otros servicios excepto actividades guber...,366218.067,312252.967,-14.735783
995,1315,32,81,0 a 5 personas,9771,9871,100,81 - Otros servicios excepto actividades guber...,366218.067,312252.967,-14.735783
996,1316,32,81,6 a 10 personas,345,348,3,81 - Otros servicios excepto actividades guber...,366218.067,312252.967,-14.735783

In [22]:
final_df = merge_df[["CVE_ENT","CODIGO","Concepto","ID_ESTRATO", "Unidades 2020", "DELTA UNIDADES_ECONOMICAS", "DELTA PIB"]]

final_df

,CVE_ENT,CODIGO,Concepto,ID_ESTRATO,Unidades 2020,DELTA UNIDADES_ECONOMICAS,DELTA PIB
0,1,21,21 - Minería,0 a 5 personas,4,1,-0.809980
1,1,21,21 - Minería,6 a 10 personas,3,0,-0.809980
2,2,21,21 - Minería,0 a 5 personas,19,3,-0.809980
3,2,21,21 - Minería,6 a 10 personas,14,-2,-0.809980
4,3,21,21 - Minería,0 a 5 personas,17,5,-0.809980
...,...,...,...,...,...,...,...
992,30,81,81 - Otros servicios excepto actividades guber...,6 a 10 personas,2190,29,-14.735783
993,31,81,81 - Otros servicios excepto actividades guber...,0 a 5 personas,15371,29,-14.735783
994,31,81,81 - Otros servicios excepto actividades guber...,6 a 10 personas,1045,19,-14.735783
995,32,81,81 - Otros servicios excepto actividades guber...,0 a 5 personas,9871,100,-14.735783
996,32,81,81 - Otros servicios excepto actividades guber...,6 a 10 personas,348,3,-14.735783

In [24]:
#Export the dataframe to a csv file
csv_path= "Output/denue_total.csv"
merge_df.to_csv(csv_path,index=False)